[build]
command = "npm run netlify-build"
publish = ".next"

[build.environment]
NODE_VERSION = "22"

[context.deploy-preview]
command = "npm run netlify-preview-build"

[context.branch-deploy]
command = "npm run netlify-preview-build"

[functions]
node_bundler = "esbuild"

[functions."article-retention"]
schedule = "17 4 * * *"

[[redirects]]
  from = "https://www.crypticwiki.net/*"
  to = "https://crypticwiki.net/:splat"
  status = 301
  force = true

[[plugins]]
package = "@netlify/plugin-nextjs"
