// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function normalizeDbConnString(raw: string) {
  let u: URL;
  try {
    u = new URL(raw);
  } catch {
    return raw;
  }

  const host = u.hostname.toLowerCase();
  const isSupabase = host.includes("supabase.co") || host.includes("supabase.com");
  const sslmode = (u.searchParams.get("sslmode") ?? "").toLowerCase();
  const shouldApplyCompat =
    isSupabase && (sslmode === "require" || sslmode === "prefer" || sslmode === "verify-ca");

  if (shouldApplyCompat && !u.searchParams.has("uselibpqcompat")) {
    u.searchParams.set("uselibpqcompat", "true");
  }

  return u.toString();
}

const useNetlifyDatabase = process.env["DATABASE_PROVIDER"] === "netlify";
const migrationDbUrl = useNetlifyDatabase
  ? process.env["NETLIFY_DB_URL"]
  : process.env["DATABASE_URL"] ??
    process.env["POSTGRES_URL_NON_POOLING"] ??
    process.env["POSTGRES_URL"];

if (!migrationDbUrl) {
  throw new Error(
    useNetlifyDatabase
      ? "DATABASE_PROVIDER=netlify requires platform-provided NETLIFY_DB_URL."
      : "Missing DB URL for migrations. Set DATABASE_URL.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: normalizeDbConnString(migrationDbUrl),
  },
});
