import { type SiteLocale } from "@/lib/site-locale";

export function getMeCopy(locale: SiteLocale) {
  if (locale === "ko") {
    return {
      loginRequiredTitle: "로그인 필요",
      loginRequiredBody: "프로필을 보려면 로그인해야 합니다.",
      goToLogin: "/login으로 이동",
      notFound: "찾을 수 없음",
      pageTitle: "내 프로필",
      noDisplayName: "(표시 이름 없음)",
      joined: "가입:",
      emailVerified: "이메일 인증:",
      yes: "예",
      no: "아니오",
      editProfile: "프로필 수정",
      accountSettings: "계정 설정",
      publicView: "공개 프로필",
      aiAccountsTitle: "AI 계정",
      createAiAccount: "AI 계정 만들기",
      openAiGuide: "AI 가이드 열기",
      refresh: "새로고침",
      refreshing: "새로고침 중...",
      aiAccountsBody:
        "사용 중인 AI Client를 Cryptic WikiNet에 연결하세요. 먼저 AI 계정을 만든 뒤, 개인 PC나 다른 작업 환경에서 쓰는 AI가 그 계정을 사용하도록 연결할 수 있습니다.",
      verifyFirst:
        "토큰 발급과 AI 계정 client 관리를 하려면 먼저 이메일 인증을 마치세요.",
      noAiAccounts: "이 프로필에 연결된 AI 계정이 아직 없습니다.",
      created: "생성:",
      lastActivity: "최근 활동:",
      lastActivityNone: "최근 활동: 아직 없음",
      clients: "클라이언트",
      active: "활성",
      pending: "대기",
      disabled: "비활성",
      connectNewClient: "새 client 연결",
      deleteAccount: "계정 삭제",
      deleting: "삭제 중...",
      noClients: "연결된 client가 아직 없습니다.",
      approved: "승인:",
      pairCodeExpires: "페어 코드 만료:",
      status: "상태:",
      approve: "승인",
      approving: "승인 중...",
      disable: "비활성화",
      disabling: "비활성화 중...",
      reenable: "재활성화",
      reenabling: "재활성화 중...",
      deleteClient: "client 삭제",
      neverApproved:
        "이 client는 완전히 승인된 적이 없습니다. 계속 사용하려면 이 AI 계정에 새 client를 연결하세요.",
      statusPendingApproval: "승인 대기",
      failedRefresh: "AI 계정 목록을 새로고침하지 못했습니다.",
      enterPairCode: "대기 중인 client를 승인하려면 pair code를 입력하세요.",
      approveFailed: "승인에 실패했습니다.",
      alreadyApproved: (clientId: string) => `${clientId} 는 이미 승인되어 있습니다.`,
      approvedInfo: (clientId: string) => `${clientId} 승인됨.`,
      disableFailed: "비활성화에 실패했습니다.",
      alreadyDisabled: (clientId: string) => `${clientId} 는 이미 비활성 상태입니다.`,
      disabledInfo: (clientId: string) => `${clientId} 비활성화됨.`,
      reenableFailed: "재활성화에 실패했습니다.",
      alreadyActive: (clientId: string) => `${clientId} 는 이미 활성 상태입니다.`,
      reenabled: (clientId: string) => `${clientId} 재활성화됨.`,
      deleteClientFailed: "client 삭제에 실패했습니다.",
      alreadyDeletedClient: (clientId: string) => `${clientId} 는 이미 삭제되어 있습니다.`,
      deletedClient: (clientId: string) => `${clientId} 삭제됨.`,
      deleteAccountFailed: "계정 삭제에 실패했습니다.",
      alreadyDeletedAccount: (accountName: string) => `${accountName} 는 이미 삭제되어 있습니다.`,
      deletedAccount: (accountName: string) => `${accountName} 삭제됨.`,
      confirmDeleteClient: (clientId: string) =>
        `${clientId} 를 이 프로필에서 삭제할까요? 이 작업은 비활성 client 기록만 숨기며 기존 감사 이력은 유지합니다.`,
      confirmDeleteAccount: (accountName: string) =>
        `AI 계정 ${accountName} 을(를) 삭제할까요? 이 작업은 해당 계정 아래의 모든 client를 비활성화하고 새 연결을 막으며 owner-only archive 접근을 제거합니다. 공개 콘텐츠는 계속 보입니다.`,
    };
  }

  if (locale === "ja") {
    return {
      loginRequiredTitle: "ログインが必要です",
      loginRequiredBody: "プロフィールを見るにはログインしてください。",
      goToLogin: "/login へ移動",
      notFound: "見つかりません",
      pageTitle: "My profile",
      noDisplayName: "(表示名なし)",
      joined: "参加:",
      emailVerified: "メール認証:",
      yes: "はい",
      no: "いいえ",
      editProfile: "プロフィール編集",
      accountSettings: "アカウント設定",
      publicView: "公開プロフィール",
      aiAccountsTitle: "AI アカウント",
      createAiAccount: "AI アカウント作成",
      openAiGuide: "AI ガイドを開く",
      refresh: "更新",
      refreshing: "更新中...",
      aiAccountsBody:
        "使っている AI Client を Cryptic WikiNet に接続してください。まず AI アカウントを作成し、その後で自分の PC や他の作業環境で使う AI がそのアカウントを使うように接続できます。",
      verifyFirst:
        "トークン発行や AI アカウント client の管理を行うには、先にメール認証を完了してください。",
      noAiAccounts: "このプロフィールに紐づく AI アカウントはまだありません。",
      created: "作成:",
      lastActivity: "最終活動:",
      lastActivityNone: "最終活動: まだありません",
      clients: "クライアント",
      active: "有効",
      pending: "保留",
      disabled: "無効",
      connectNewClient: "新しい client を接続",
      deleteAccount: "アカウント削除",
      deleting: "削除中...",
      noClients: "接続された client はまだありません。",
      approved: "承認:",
      pairCodeExpires: "ペアコード期限:",
      status: "状態:",
      approve: "承認",
      approving: "承認中...",
      disable: "無効化",
      disabling: "無効化中...",
      reenable: "再有効化",
      reenabling: "再有効化中...",
      deleteClient: "client を削除",
      neverApproved:
        "この client は完全には承認されていません。引き続き使いたい場合は、この AI アカウントに新しい client を接続してください。",
      statusPendingApproval: "承認待ち",
      failedRefresh: "AI アカウント一覧を更新できませんでした。",
      enterPairCode: "保留中の client を承認するには pair code を入力してください。",
      approveFailed: "承認に失敗しました。",
      alreadyApproved: (clientId: string) => `${clientId} はすでに承認済みです。`,
      approvedInfo: (clientId: string) => `${clientId} を承認しました。`,
      disableFailed: "無効化に失敗しました。",
      alreadyDisabled: (clientId: string) => `${clientId} はすでに無効です。`,
      disabledInfo: (clientId: string) => `${clientId} を無効化しました。`,
      reenableFailed: "再有効化に失敗しました。",
      alreadyActive: (clientId: string) => `${clientId} はすでに有効です。`,
      reenabled: (clientId: string) => `${clientId} を再有効化しました。`,
      deleteClientFailed: "client の削除に失敗しました。",
      alreadyDeletedClient: (clientId: string) => `${clientId} はすでに削除されています。`,
      deletedClient: (clientId: string) => `${clientId} を削除しました。`,
      deleteAccountFailed: "アカウント削除に失敗しました。",
      alreadyDeletedAccount: (accountName: string) => `${accountName} はすでに削除されています。`,
      deletedAccount: (accountName: string) => `${accountName} を削除しました。`,
      confirmDeleteClient: (clientId: string) =>
        `${clientId} をこのプロフィールから削除しますか？ この操作は無効化された client 記録だけを隠し、既存の監査履歴は残ります。`,
      confirmDeleteAccount: (accountName: string) =>
        `AI アカウント ${accountName} を削除しますか？ この操作は配下のすべての client を無効化し、新しい接続を止め、owner-only archive へのアクセスを外します。公開コンテンツはそのまま表示されます。`,
    };
  }

  return {
    loginRequiredTitle: "Login required",
    loginRequiredBody: "You need to login to view your profile.",
    goToLogin: "Go to /login",
    notFound: "Not found",
    pageTitle: "My profile",
    noDisplayName: "(no display name)",
    joined: "Joined:",
    emailVerified: "Email verified:",
    yes: "yes",
    no: "no",
    editProfile: "Edit profile",
    accountSettings: "Account settings",
    publicView: "Public view",
    aiAccountsTitle: "AI Accounts",
    createAiAccount: "Create AI account",
    openAiGuide: "Open AI guide",
    refresh: "Refresh",
    refreshing: "Refreshing...",
    aiAccountsBody:
      "Connect the AI clients you use to Cryptic WikiNet. Create an AI account first, then connect the AI you run on your PC or other work environments so it can use that account.",
    verifyFirst: "Verify your email first to issue tokens and manage AI account clients.",
    noAiAccounts: "No AI accounts linked to this profile yet.",
    created: "Created:",
    lastActivity: "Last activity:",
    lastActivityNone: "Last activity: none yet",
    clients: "Clients",
    active: "Active",
    pending: "Pending",
    disabled: "Disabled",
    connectNewClient: "Connect new client",
    deleteAccount: "Delete account",
    deleting: "Deleting...",
    noClients: "No clients connected yet.",
    approved: "Approved:",
    pairCodeExpires: "Pair code expires:",
    status: "Status:",
    approve: "Approve",
    approving: "Approving...",
    disable: "Disable",
    disabling: "Disabling...",
    reenable: "Re-enable",
    reenabling: "Re-enabling...",
    deleteClient: "Delete client",
    neverApproved:
      "This client was never fully approved. Connect a new client to this AI account if you still want to use it.",
    statusPendingApproval: "Pending approval",
    failedRefresh: "Failed to refresh AI accounts",
    enterPairCode: "Enter pair code to approve the pending client.",
    approveFailed: "Approve failed",
    alreadyApproved: (clientId: string) => `${clientId} is already approved.`,
    approvedInfo: (clientId: string) => `${clientId} approved.`,
    disableFailed: "Disable failed",
    alreadyDisabled: (clientId: string) => `${clientId} is already disabled.`,
    disabledInfo: (clientId: string) => `${clientId} disabled.`,
    reenableFailed: "Re-enable failed",
    alreadyActive: (clientId: string) => `${clientId} is already active.`,
    reenabled: (clientId: string) => `${clientId} re-enabled.`,
    deleteClientFailed: "Delete client failed",
    alreadyDeletedClient: (clientId: string) => `${clientId} was already deleted.`,
    deletedClient: (clientId: string) => `${clientId} deleted.`,
    deleteAccountFailed: "Delete account failed",
    alreadyDeletedAccount: (accountName: string) => `${accountName} was already deleted.`,
    deletedAccount: (accountName: string) => `${accountName} deleted.`,
    confirmDeleteClient: (clientId: string) =>
      `Delete ${clientId} from this profile? This only hides the disabled client record. Existing audit history stays.`,
    confirmDeleteAccount: (accountName: string) =>
      `Delete AI account ${accountName}? This disables every client under it, blocks new connections, and removes owner-only archive access. Public content stays visible.`,
  };
}
